### ISSUE TITLE
Bug in predict_embed function

### ISSUE THREAD

**Issue by manikbhandari** [pfnet-research/contextual_augmentation#4]
I think there is a slight bug in the predict_embed function. According to the code:

```python
    for i, x in enumerate(xs):
            new_out.append(eos)  
            new_out.append(out_concat[count:count + len(xs) - 2])
            new_out.append(eos)
            count += len(xs) - 2
        out_concat = F.concat(new_out, axis=0)
```

But xs is the full batch and len(xs) is the batch size. I think it should be 
```python
for i, x in enumerate(xs):
            new_out.append(eos)  
            new_out.append(out_concat[count:count + len(x) - 2])
            new_out.append(eos)
            count += len(x) - 2
        out_concat = F.concat(new_out, axis=0)
```
i.e. len(x) instead of len(xs) since x is an input sentence.

Please let me know if I'm making a mistake somewhere.

Thanks

**Comment by hisyatokaku** [comment]
+1

Also, it seems that the accuracy on stsa.fine validaition data decreases by 3-4% when len(xs) parts got changed into len(x).

Thanks,

**Comment by soskek** [comment]
Thanks! I fixed this implementation.
