### ISSUE TITLE
ModuleNotFoundError: No module named 'progressbar' problem

### ISSUE THREAD

**Issue by shokosanma** [pfnet-research/contextual_augmentation#5]
When you have "ModuleNotFoundError: No module named 'progressbar' " problem, use
`pip install progressbar2`
not
`pip install progressbar`

**Comment by GW-S** [comment]
hey,I know this.
you have to not use progressbar , you should go into code ,change code ,don't use progressbar,
delete this thing.this progressbar is not cant be remove
