### ISSUE TITLE
How you used the final model.npz file to do contextual augmentation in results_caug folder ?  

### ISSUE THREAD

**Issue by surajiiitd** [pfnet-research/contextual_augmentation#6]
When i am trying to load model using model = nets.BiLanguageModel(
        50000, 1024, 1, 0.01)
chainer.serializers.load_npz(path,model)

It is giving error as:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-57-5d179f2ba41d> in <module>()
----> 1 chainer.serializers.load_npz(path,model)

~/.local/lib/python3.6/site-packages/chainer/serializers/npz.py in load_npz(file, obj, path, strict, ignore_names)
    240         d = NpzDeserializer(
    241             f, path=path, strict=strict, ignore_names=ignore_names)
--> 242         d.load(obj)

~/.local/lib/python3.6/site-packages/chainer/serializer.py in load(self, obj)
     81 
     82         """
---> 83         obj.serialize(self)

~/.local/lib/python3.6/site-packages/chainer/link.py in serialize(self, serializer)
   1034         d = self.__dict__  # type: tp.Dict[str, Link]
   1035         for name in self._children:
-> 1036             d[name].serialize(serializer[name])
   1037 
   1038 

~/.local/lib/python3.6/site-packages/chainer/link.py in serialize(self, serializer)
   1246         super(ChainList, self).serialize(serializer)
   1247         for idx, child in enumerate(self._children):
-> 1248             child.serialize(serializer['%d' % idx])

~/.local/lib/python3.6/site-packages/chainer/link.py in serialize(self, serializer)
    653         for name in self._params:
    654             param = d[name]
--> 655             data = serializer(name, param.data)  # type: types.NdArray
    656             if param.data is None and data is not None:
    657                 # Initialize the parameter here

~/.local/lib/python3.6/site-packages/chainer/serializers/npz.py in __call__(self, key, value)
    173                     'list of them.')
    174 
--> 175         dataset = self.npz[key]
    176         if dataset[()] is None:
    177             return None

/usr/local/lib/python3.6/dist-packages/numpy/lib/npyio.py in __getitem__(self, key)
    253                 return self.zip.read(key)
    254         else:
--> 255             raise KeyError("%s is not a file in the archive" % key)
    256 
    257 

KeyError: 'encoder_bw/0/w4 is not a file in the archive'
Please suggest method to load the final model to get the augmented data for test data.

**Comment by soskek** [comment]
Sorry for my late reply. I have no idea. This works in my environment if I follow README.
